name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean and Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Clean binaries to avoid rejection
          rm -rf examples/
          
          # 2. Configure Git
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 3. Create a temporary 'deploy' branch with no binaries
          git checkout -b deploy
          git add .
          git commit -m "chore: clean deployment"
          
          # 4. Force push the clean branch to the Hugging Face main branch
          # Using exact lowercase 'Ratina_face'
          git push --force https://ImdataScientistSachin:$HF_TOKEN@huggingface.co/spaces/ImdataScientistSachin/Ratina_face deploy:main
